### ISSUE TITLE
Allow to specify max payload size, header size and etc

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1123]
### Describe your problem(s)
Currently the maximum payload size can pass through the gateway is maximum. We need a way to specify the max payload size, header size, URI length and keep alive conditions in the listener level of the microgateway

### Describe your solution
We need to introduce a set of configurations under the [listenerConfig] section of the micro-gw.conf file

**Comment by Rajith90** [comment]
We have introduced the following set of configuration under the [] section of the micro-gw.conf

```toml
  #http1 Settings
  #Can be set to either `AUTO`, which respects the `connection` header, or `ALWAYS`,
  # which always keeps the connection alive, or `NEVER`, which always closes the connection
  keepAlive = "AUTO"
  # Defines the maximum number of requests that can be processed at a given time on a single connection.
  # By default 10 requests can be pipelined on a single connection and user can change this limit appropriately.
  maxPipelinedRequests = 10
  # Maximum allowed length for a URI. Exceeding this limit will result in a `414 - URI Too Long` response.
  maxUriLength = 4096
  # Maximum allowed size for headers. Exceeding this limit will result in a `413 - Payload Too Large` response.
  maxHeaderSize = 8192
  # Maximum allowed size for the entity body. By default it is set to -1 which means there is no
  # restriction `maxEntityBodySize`, On the Exceeding this limit will result in a`413 - Payload Too Large` response.
  maxEntityBodySize = -1
```
