### ISSUE TITLE
Need a solution to add few custom filters before and after the default micro gateway handlers

### ISSUE THREAD

**Issue by amalkasubasinghe** [wso2/product-microgateway#1181]
### Describe your problem(s)
Need a solution to add few custom filters before and after the default micro gateway handlers
There are cases we need to add filters before the API Schema Validation too.

### How will you implement it

---

**Comment by Rajith90** [comment]
With the fix developers can write their own custom filters and plug that in to the project. Filters are applied to all the APIs exposed via the gateway. 
We can define the filters in the deployment-config.toml file in the project conf (<PROJECT_HOME>/conf) folder. This project is the microgateway project which is generated when run the `micro-gw init <PROJECT_NAME>` command.

```toml
[[filters]]
    name = "Filter1"
    position = 0
[[filters]]
    name = "Filter2"
    position = 5
[[filters]]
    name = "Filter3"
    position = 6
```

Users can define the index in which their custom filter should be plugged in.
Here is the default filter chain order in mgw
`grpcFilter, preAuthnFilter, authenticationFilter, authorizationFilter,
        validationRequestFilter, throttleFilter, analyticsFilter, validationResponseFilter, extensionFilter`

When user specifies the index for their custom filter the existing filter chain will be re ordered accordingly.
