### ISSUE TITLE
Open API production endpoint having special characters cause request failures

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1207]
### Description:
If the x-wso2-production-endpoint or server object urls contains special characters, it will proxy the request to wrong endpoint
### Steps to reproduce:
1. Define the production endpoint as below in the open API definition
```yaml
x-wso2-endpoints:
- 3b8e54f729cb697e9fecdd36e4e329bb:
    urls:
    - 'https://postman-echo.com/post?foo1=bar1&foo2=bar2'
    type: http
```
2. Then build and invoke the gateway
3. This will forward the request to the endpoint https://postman-echo.com/post?foo1=
### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
