### ISSUE TITLE
Switch default persistent revoked jwt retrieval to APIM service instead of etcd

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1327]
### Describe your problem(s)
Currently microgateway pulls the revoked jwts from an etcd server during the startup. But when using API Manager with microgateway, APIM exposes a service to pull all the revoked tokens. The default implementation should be switched to this one. ETCD will also be supported as earlier.

### Describe your solution
Pulls the revoked tokens from the /revokedjwt endpoint exposes by the API manager(Traffic manager node).

### How will you implement it

---

**Comment by Rajith90** [comment]
In the config section we have made the following changes. 
Instead of honouring the previous config `useDefault` which tells to use the default etcd or custom implementation, we have introduced the config called `type`. This can be either "default" which pulls from APIM, "etcd" pulls from etcd or "custom" where developers need to implement jwt retrieval during server startup.  
And also `hostname` also replaced as `endpointURL`. Still hostname also supported to maintain backward compatibility.
```toml
[tokenRevocationConfig.persistent]
    enablePersistentStorageRetrieval = false
    # Use APIM as the default persistent storage. Other types are "etcd" and "custom"
    type = "default"
    # The hostname of your persistent storage server (e.g.: <etcd-server-access-URL>/<service>/keys/jti/)
    endpointURL = "https://localhost:9443/internal/data/v1"
    # The username of your persistent storage server
    username = "root"
    # The password of your persistent storage server
    password = "root"
```
