### ISSUE TITLE
CORS Filter for the proxy

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1494]
### Describe your problem(s)
Apply cors filter inside the proxy, based on API level.

### Describe your solution

The configuration needs to be provided within the openAPI definition using the vendor extensions. Here is a sample configuration. 

```
x-wso2-cors:
  enabled: true #default 
  accessControlAllowOrigins:
    - test.com
    - example.com
  accessControlAllowHeaders:
    - Authorization
    - Content-Type
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
  accessControlAllowCredentials: true
```
if the enabled sub-property is not provided, it is considered to be true (default value). 

### How will you implement it

Needs to engage the envoy inbuilt cors filter as a HTTP filter. 
[1] https://www.envoyproxy.io/docs/envoy/v1.16.0/start/sandboxes/cors.html
[2] https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-corspolicy

---
