### ISSUE TITLE
Read config.toml string values from environment variables

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1668]
### Describe your problem(s)
Certain fields like passwords and other sensitive data should be set as environment variables. 

### Describe your solution
Specify a way to define env variable for a certain config key and read it from environment variable.

### How will you implement it
For the enforcer side values enforcer will resolve the env values
```toml
[enforcer.apimCredentials]
    username="admin"
    password="$env{apim_admin_pwd}"
```
Then we should set the value as below
`export apim_admin_pwd=admin`

for the adapter side configs adapter will resolve the value from env variable.
```toml
[[adapter.server.users]]
username = "admin"
password = "$env{adapter_admin_pwd}"
```
Then we should set the value as below.
`export adapter_admin_pwd=admin`

---
