### ISSUE TITLE
Throttle eventpublisher password is not resolved from ENV vars

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#1767]
### Description:

Throttle publisher password in the config is not resolve from env vars when configured that way.
### Steps to reproduce:
- enable throttling and configure publisher password similar to below.
- start enforcer and check the errors. it says invalid username password when connecting to TM
```toml
  [enforcer.throttling.publisher]
    # Credentials required to establish connection between Traffic Manager
    username = "admin"
    password = "$env{cp_admin_pwd}"
```
### Affected Product Version:

4.0.0-m10-snapshot

### Environment details (with versions):
- OS: Mac
- Client:
- Env (Docker/K8s):
