### ISSUE TITLE
Add capability to envoy-mgw remove auth header from out message

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1780]
### Describe your problem(s)
There should be an config to disable or enable whether the authorization header should be sent to the back end.
If this is disabled the gateway will not sent the authorization header value to the back end. And it will override by api Level authorization header

### How will you implement it

---

**Comment by Rajith90** [comment]
```toml
[security.adapter]
  enableOutboundAuthHeader = false
  authorizationHeader = "authorization"
```
above config is added in order to support this feature. This config was read by the adapter and configures the router using xds to remove the auth header from the outbound message to back end
