### ISSUE TITLE
Support endpoint security given in API specification

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1945]
### Description:

endpoint security provided in API definition is not considered.
e.g.
```
x-wso2-production-endpoints:
  securityConfig: 
      type: basic
      Username: <username>
```

[1] https://mg.docs.wso2.com/en/latest/how-tos/endpoints/defining-a-backend-security-scheme/

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
