### ISSUE TITLE
Support setting Dynamic endpoints using interceptors

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2236]
### Describe your problem(s)

Selecting the upstream cluster at request time.

### Describe your solution

1. Define following extension and add your desired dynamic endpoints 
```
x-wso2-endpoint:
- myEndpoint1: 
    urls:
    - https://localhost:2380/v1
    type: failover
```
This will register a cluster for your dynamic endpoints under the following name.
e.g.
`carbon.super_myEndpoint1_xwso2cluster_localhost_SwaggerPetstore1.0.5` : `<organizationID>_<EndpointName>_xwso2cluster_<vHost>_<API name><API version>`

2. In your request interceptor, set `x-wso2-cluster-header` value to this cluster name.
e.g.
```
x-wso2-cluster-header: carbon.super_myEndpoint1_xwso2cluster_localhost_SwaggerPetstore1.0.5
```

### How will you implement it

---
