### ISSUE TITLE
Dynamic endpoints not supporting with a basePath in the service URL

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2327]
### Description:
Dynamic endpoints not supporting with a basePath in the service URL

### Steps to reproduce:

```yaml
x-wso2-endpoints:
  - myDynamicEndpoint:
      urls:
        - https://mockBackend:2382/some-path
      type: loadbalance
```

Here "some-path" is not supported. When invoking the API it invoke the resource relative to `https://mockBackend:2382/`

Assumes this is because in routes we are substituting the path with a regex. So if we can not fix this issue then we should force user not set a context path (in the config we should get host, port and scheme or in docs we should mension this)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
