### ISSUE TITLE
Support endpoint referencing

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2344]
### Describe your problem(s)

Support the following
```
x-wso2-production-endpoints: "#/x-wso2-endpoints/<endpoint-name>"
...
x-wso2-endpoints:
  - <endpoint-name1>:
      urls:
      - <url1>
```
example:
```
x-wso2-production-endpoints: "#/x-wso2-endpoints/myEndpoint1"
...
x-wso2-endpoints:
  - myEndpoint1:
      urls:
      - https://localhost:2380/v1
  - myEndpoint2:
      urls:
      - https://localhost:2382/v2
```

### How will you implement it

---
