### ISSUE TITLE
Refer prod, sand endpoints from endpoint reference

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2390]
### Describe your problem(s)

Support the following format;
https://mg.docs.wso2.com/en/latest/how-tos/endpoints/defining-endpoints-in-an-openapi-definition/#endpoint-object
```
x-wso2-production-endpoints: "#/x-wso2-endpoints/<endpoint-name>"
...
x-wso2-endpoints:
  - <endpoint-name1>:
      urls:
      - <url1>
  - <endpoint-name2>:
      urls:
      - <url2>
```

### How will you implement it

---
