### ISSUE TITLE
Improve interceptor extension

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2417]
### Describe your problem(s)

support following extension option `serviceURL` instead of host, type, port.
```
x-wso2-request-interceptor:
  serviceURL: https://xml-interceptor:9081
  includes:
    - request_body
```

### How will you implement it

---
