### ISSUE TITLE
Performance test results with interceptors

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2433]
### Describe your problem(s)
Performance test results with interceptors

### How will you implement it
- Router 1.0.0-alpha, 1CPU, 500MiB and --concurrancy=2
- Run perf test with 1KiB - real-world scenario payload
- Only with request interceptor flow
- Get results for the following three scenarios
  - Without interceptors - 100
  - Only with interceptors - 100
  - With - 50 and Without - 50 interceptors

#### Interceptor Service
- Lang: Ballerina
- Resources
  - CPU: 1
  - Memory: 500MiB
- Read the request body (1KiB - JSON)
- Rreplace a header (`content-type: application/xml`)
- Set request body (1KiB - XML)

---

**Comment by renuka-fernando** [comment]
Interceptor service impl: [interceptor.zip](https://github.com/wso2/product-microgateway/files/7554473/interceptor.zip)
Router with interceptor cert:  [router.zip](https://github.com/wso2/product-microgateway/files/7554475/router.zip)
Sample payloads:  [payloads.zip](https://github.com/wso2/product-microgateway/files/7554476/payloads.zip)

**Comment by renuka-fernando** [comment]
Related Open API content
```yaml
    x-wso2-request-interceptor:
      host: xml-interceptor
      includes:
        - request_body
      port: 9081
      scheme: https
```
