### ISSUE TITLE
Undeploy an API from a vhost and in a specific environment using APICTL

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2451]
### Description:
Undeploy an API from a vhost and in a specific environment using APICTL

### Steps to reproduce:
1. Setup two environment `Default` and `US` - [vhost-docker-compose-setup.tar.gz](https://github.com/wso2/product-microgateway/files/7571512/vhost-docker-compose-setup.tar.gz)
2. Deploy petstore API to two labels, with following deployment-enviornments file  [petstore.tar.gz](https://github.com/wso2/product-microgateway/files/7571527/petstore.tar.gz)

```yaml
type: deployment_environments
version: v4.0.0
data:
 -
   displayOnDevportal: true
   deploymentEnvironment: US
 -
   displayOnDevportal: true
   deploymentVhost: localhost
   deploymentEnvironment: US
 -
   displayOnDevportal: true
   deploymentEnvironment: Default

```
3. apictl mg deploy api -e dev -k -f petstore/
4. $ apictl mg get apis -e dev -k
Limit flag not set. Set to default: 25
APIs total: 2 received: 2
NAME                VERSION             TYPE                CONTEXT             GATEWAY_ENVS        VHOST
SwaggerPetstore     1.0.5               HTTP                /v2                 [US]                us.wso2.com
SwaggerPetstore     1.0.5               HTTP                /v2                 [US Default]        localhost
5. $ apictl mg undeploy api -n SwaggerPetstore -v 1.0.5 -e dev -k --vhost localhost -g US
API undeployed from microgateway successfully!
6. $ apictl mg get apis -e dev -k
Limit flag not set. Set to default: 25
APIs total: 2 received: 2
NAME                VERSION             TYPE                CONTEXT             GATEWAY_ENVS        VHOST
SwaggerPetstore     1.0.5               HTTP                /v2                 [US]                us.wso2.com
SwaggerPetstore     1.0.5               HTTP                /v2                 [Default]           localhost
7. $ TOKEN=$(curl -X POST "https://localhost:9095/testkey" -H "Authorization: Basic YWRtaW46YWRtaW4=" -k -v)
8. $ curl -X GET "https://localhost:9195/v2/store/inventory" -H "accept: application/json" -H "Authorization: Bearer $TOKEN" -k
{"test_status":6,"sold":20,"string":217,"bad":4,"sold ":1,"alive":1,"unavailable":1,"TESTEB":1,"pending":13,"available":662,"solt":1,"null":2,"connector":1,"extinct":3,"status":1}

Could invoke the undeployed API.

### Affected Product Version:
CC v1.0.0 beta-snapshot

### Environment details (with versions):
- OS: mac
- Client: curl
- Env (Docker/K8s): docker

---
