### ISSUE TITLE
Handling Operation Policy Spec and Definition

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2655]
### Describe your problem(s)
Handling Operation Policy Spec and Definition

### Describe your solution

Sample Spec

```yaml
type: operation_policy_specification
version: v4.1.0
data:
 category: Mediation
 name: addRequestHeader
 displayName: Set Header
 description: With this policy, user can add a new header to the request
 applicableFlows:
  - request
 supportedGateways:
  - CC
 supportedApiTypes:
  - REST
 policyAttributes:
  -
   name: headerName
   displayName: Header Name
   description: Name of the header to be added
   validationRegex: /^\S+$/
   type: String
   required: true
  -
   name: headerValue
   displayName: Header Value
   description: Value of the header
   validationRegex: ""
   type: String
   required: true
 multipleAllowed: true
```

Sample Policy
```yaml
definition:
 action: SET_HEADER
 parameters:
   headerName: {{ .Params.headerName }}
   headerValue: {{ .Params.headerValue }}
```

### How will you implement it

---
