### ISSUE TITLE
Remove operation policy validation on "multipleAllowed" in policy Spec

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2668]
### Describe your problem(s)
```yaml
type: operation_policy_specification
version: v4.1.0
data:
  category: Mediation
  name: fooRewriteResourcePath
  displayName: Rewrite Resource Path
  description: With this policy, user can add a new header to the request 22
  applicableFlows:
   - request #["request","response","fault"]
  supportedGateways:
   - CC #["Synapse", "CC"]
  supportedApiTypes:
   - REST #["REST","GRAPHQL", "Streaming"]
  policyAttributes:
   -
    name: fooResourcePath  #TODO DO we need this
    displayName: Current Method
    description: Name of the header to be added
    validationRegex: /^\S+$/
    type: String
    required: true
   -
    name: fooIncludeQueryParams
    displayName: Include query params
    description: Value of the header
    type: Boolean
    required: false
  multipleAllowed: false
```

Remove validation based on `multipleAllowed`.

---
