### ISSUE TITLE
Error while applying generated Kubernetes yaml

### ISSUE THREAD

**Issue by tony2k84** [wso2/product-microgateway#2674]
### Description:
While applying Kubernetes yaml - it throws the below exception:
➜  wso2-mg kubectl apply -f /Users/abhishek/code/examples/wso2-mg/sample-mgw-k8s/target/gen/target/kubernetes/sample-mgw-k8s
service/httpservice unchanged
service/httpsservice unchanged
configmap/sample-space-1--1-0-0-ballerina-conf-config-map configured
configmap/sample-space-2--1-0-0-ballerina-conf-config-map configured
The Deployment "k8s" is invalid: spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/home/ballerina/conf/": must be unique

### Steps to reproduce:
1. micro-gw build sample
2. Add two services under same MGW project
3. micro-gw build sample-mgw-k8s
4. docker save sample-mgw-k8s:latest > ./sample-mgw-k8s/sample-mgw-k8s.tar
5. kubectl apply -f /Users/abhishek/code/examples/wso2-mg/sample-mgw-k8s/target/gen/target/kubernetes/sample-mgw-k8s

### Affected Product Version:
3.2.0

### Environment details (with versions):
- OS: Mac M1
- Client: NA
- Env (Docker/K8s): Docker/K8s

**Comment by tony2k84** [comment]
the default generated YAML files contains two mount points with same name since I have two services inside a single MGW project.

```
volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "sample-space-1--1-0-0-ballerina-conf-config-map-volume"
          readOnly: false
        - mountPath: "/home/ballerina/conf/"
          name: "sample-space-2--1-0-0-ballerina-conf-config-map-volume"
          readOnly: false
```
