### ISSUE TITLE
Support Multiple Trusted JWT Issuers for microgateway

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-microgateway#271]
**Description:**
In the current design of the micro-gateway, we can use the micro-gateway.conf file to configure information about one trusted issuer as below.

```
[jwtTokenConfig]
issuer="https://sts.wso2.com"
audience="http://org.wso2.apimgt/gateway"
certificateAlias="wso2apim"
trustStore.path="${ballerina.home}/bre/security/ballerinaTruststore.p12"
trustStore.password="ballerina"
```

This only allows us to validate only JWTs issued by the configured trusted JWT issuer at the micro gateway.

As an improvement it would better if we could support multiple trusted JWT issuers.

**Suggested Labels:**
Improvement

**Affected Product Version:**
2.6.0

**Comment by praminda** [comment]
Depends on ballerina-platform/ballerina-lang#14966

**Comment by Rajith90** [comment]
We are planning to support below config to support multiple issuers

`[jwtTokenConfig]
issuer="https://localhost:9444/oauth2/token"
audience="http://org.wso2.apimgt/gateway"
certificateAlias="wso2apim"


[jwtTokenConfig1]
issuer="issuer1"
audience="aud1"
certificateAlias="alias1"
`

**Comment by praminda** [comment]
Is there a possibility of getting ballerina toml array parsing issue. `jwtTokenConfig1,2,3...` doesn't look ok to me

**Comment by mefarazath** [comment]
> Is there a possibility of getting ballerina toml array parsing issue fixed. `jwtTokenConfig1,2,3...` doesn't look ok to me

Yes. An array would look clean

**Comment by Rajith90** [comment]
ATM we can not read arrays from ballerina config API [1]. Ideally we should use the toml arrays. But seems its not supported yet.

[1] - https://github.com/ballerina-platform/ballerina-lang/issues/10633

**Comment by praminda** [comment]
Hmm, Can we do something like,
```toml
[jwtTokenConfig]
[jwtTokenConfig.0]
issuer=""
audience=""
certificateAlias=""

[jwtTokenConfig.1]
issuer=""
audience=""
certificateAlias=""
```
Still look bit weird and it will break the old config interface.

**Comment by Rajith90** [comment]
This seems ok as well, as you mentioned this would break the existing config. Thats why I suggested the earlier config that would not break the existing config

**Comment by praminda** [comment]
@Rajith90 Can ballerina process the toml arrays now?

**Comment by Rajith90** [comment]
This is the final configuration supported in 3.1.0 version

```toml
# JWT token authorization configurations. You can provide multiple JWT issuers
# Issuer 1
[[jwtTokenConfig]]
  issuer = "https://localhost:9443/oauth2/token"
  audience = "http://org.wso2.apimgt/gateway"
  certificateAlias = "wso2apim310"
  # Validate subscribed APIs
  validateSubscription = false
# Issuer 2
[[jwtTokenConfig]]
  issuer = "https://host:port/issuer"
  audience = "http://org.wso2.apimgt/gateway"
  certificateAlias = "alias"
  # Validate subscribed APIs
  validateSubscription = false
```
