### ISSUE TITLE
Check behaviour when interceptor service applied from both vender extension and API policy

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2755]
### Describe your problem(s)
Check behaviour when interceptor service is applied from both vender extension and API policy.

#### vendor extension
```yaml
x-wso2-request-interceptor:
  serviceURL: https://vender-extension-api:2371
  includes:
    - request_headers
    - request_body
    - invocation_context
```

#### API policy

```yaml
       -
        policyName: ccCallInterceptorService
        policyVersion: v1
        policyId: 749f6393-b59d-43fb-9cca-f4c850dea27b
        parameters:
          interceptorServiceURL: http://interceptor
          includes: "request_headers,request_body"
```

### How will you implement it

---

**Comment by renuka-fernando** [comment]
### Integration Analysis

API Policy overrides, swagger vender extensions

#### API Yaml

```yaml

  operations:
   -
    id: ""
    target: /*
    verb: GET
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
    operationPolicies:
      request:
       -
        policyName: ccCallInterceptorService
        policyVersion: v1
        policyId: 749f6393-b59d-43fb-9cca-f4c850dea27b
        parameters:
          interceptorServiceURL: http://interceptor
          includes: "request_headers,request_body"
```

#### Swagger

```yaml
openapi: 3.0.1
info:
  title: Test
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
x-wso2-request-interceptor: # API level interceptor definition
  serviceURL: https://vender-extension-api:2371
  includes:
    - request_headers
    - request_body
    - invocation_context
paths:
  /*:
    get:
      x-wso2-request-interceptor: # API level interceptor definition
        serviceURL: https://vender-extension-operation:2371
        includes:
          - request_headers
          - request_body
          - invocation_context
      responses:
        "200":
          description: OK
    put:
      responses:
        "200":
          description: OK
```

#### Lua script for the resource /*

```lua

local interceptor = require 'home.wso2.interceptor.lib.interceptor'
local resp_flow_list = {} 
local inv_context = {
	organizationId = "carbon.super",
	basePath = "/any/v1",
	supportedMethods = "PUT DELETE GET PATCH POST",
	apiName = "Test",
	apiVersion = "1.0.0",
	pathTemplate = "/*",
	vhost = "localhost",
	prodClusterName = "carbon.super_clusterProd_localhost_Test1.0.0",
	sandClusterName = "carbon.super_clusterSand_localhost_Test1.0.0"
}

local req_flow_list = {DELETE = {invocationContext = true, requestHeaders = true, requestBody = true, requestTrailer = false},GET = {invocationContext = false, requestHeaders = true, requestBody = true, requestTrailer = false},PATCH = {invocationContext = true, requestHeaders = true, requestBody = true, requestTrailer = false},POST = {invocationContext = true, requestHeaders = true, requestBody = true, requestTrailer = false},PUT = {invocationContext = true, requestHeaders = true, requestBody = true, requestTrailer = false},}
local req_call_config = {DELETE = {cluster_name = "carbon.super_reqInterceptor_localhost_Test1.0.0", timeout = 20000},GET = {cluster_name = "carbon.super_reqInterceptor_localhost_Test1.0.0_9746ceb8-361d-4d81-bea4-d54da8f912c30", timeout = 20000},PATCH = {cluster_name = "carbon.super_reqInterceptor_localhost_Test1.0.0", timeout = 20000},POST = {cluster_name = "carbon.super_reqInterceptor_localhost_Test1.0.0", timeout = 20000},PUT = {cluster_name = "carbon.super_reqInterceptor_localhost_Test1.0.0", timeout = 20000},}
function envoy_on_request(request_handle)
	interceptor.handle_request_interceptor(
		request_handle, req_call_config, req_flow_list, resp_flow_list, inv_context
	)
end

function envoy_on_response(response_handle)
end
```

#### Clusters
```json
       "cluster_name": "carbon.super_reqInterceptor_localhost_Test1.0.0",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "vender-extension-api",
              "port_value": 2371
             }
            }
           }
```

```json
"cluster_name": "carbon.super_reqInterceptor_localhost_Test1.0.0_9746ceb8-361d-4d81-bea4-d54da8f912c30",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "interceptor",
              "port_value": 80
             }
            }
           }
          }
         ]
        }
       ]
```
