### ISSUE TITLE
Support Operation Level - API Policies

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2756]
### Describe your problem(s)
Envoy support HTTP header based route matches.

```yaml
static_resources:
  listeners:
    - name: http_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 9080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/hello"
                            headers:
                              name: ":method"
                              exact_match: "POST"
                          route:
                            cluster: httpbin-cluster
                            regex_rewrite:
                              pattern:
                                google_re2: {}
                                regex: "^/hello/([^/]+)"
                              substitution: "/anything/hello-world/post/"
                        - match:
                            prefix: "/hello"
                            headers:
                              name: ":method"
                              exact_match: "PUT"
                          route:
                            cluster: httpbin-cluster
                            regex_rewrite:
                              pattern:
                                google_re2: {}
                                regex: "^/hello/([^/]+)"
                              substitution: "/anything/hello-put/put/"
                        - match:
                            prefix: "/hello"
                            headers:
                              name: ":method"
                              exact_match: "GET"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "Hello World - GET DIRECT"
                        - match: { prefix: "/" }
                          direct_response:
                            status: 200
                            body:
                              inline_string: "Hello World"
                http_filters:
                  - name: envoy.filters.http.router
```

### Describe your solution
Sample
https://github.com/renuka-fernando/demos/tree/master/envoy-operation-level-support

### How will you implement it

---
