### ISSUE TITLE
Null "InvocationContext " in Java sample interceptor service

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2901]
### Description:

Null is returned for "InvocationContext" from sample Java interceptor service when `invocation_context` is added in `includes` section of OAS.

#### Temporary fix

Change `@JsonProperty("InvocationContext") -> @JsonProperty("invocationContext")` in 
https://github.com/wso2/product-microgateway/blob/d92ea73e255b3642e0f12eb44619b981d0013d35/samples/interceptors/java/spring-server-generated/src/main/java/io/swagger/model/RequestHandlerRequestBody.java#L31

### Steps to reproduce:

- Add sample java interceptor service
- Additionally add `invocation_context` in includes
- Check invocation_context field in the model object.

```
x-wso2-request-interceptor:
  serviceURL: [http|https]://<host>[:<port>]
  includes: # any of following
    - request_headers
    - request_body
    - request_trailers
    - invocation_context
```

### Affected Product Version:
Choreo Connect 1.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
