### ISSUE TITLE
Config.toml is not mounted to the CC deployment in k8s configs

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#3275]
### Description

$subject

```yaml
            - mountPath: /home/wso2/conf/config.toml
              subPath: config.toml
              name: config-toml-vol
```

is not available in the k8s mounts of the Enforcer.

### Version

1.2.0-beta
