### ISSUE TITLE
Remove config-toml-vol in CC Deployment k8s config

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#3276]
### Description

Following is not required for CC Deployment
```yaml
        - name: config-toml-vol
          configMap:
            name: config-toml
```

### Version

1.2.0-beta
