### ISSUE TITLE
[CC] Add Prometheus Support for Choreo Connect

### ISSUE THREAD

**Issue by Avishka-Shamendra** [wso2/product-microgateway#3427]
### Problem

Choreo-Connect currently doesn't support publishing metrics to Prometheus.

### Solution

Expose metrics endpoints of router, enforcer and adapter to Prometheus.

**Comment by Avishka-Shamendra** [comment]
# [Feature Docs] Enabling Promethues Metrics on CC

## On Docker Compose

#### Router

- No configuration is required. Metrics are accessible via the router admin port at the `stats/prometheus` endpoint.

#### Enforcer
- Include the following as an environment variable in the `docker-compose.yml` for the enforcer. Replace `ENFORCER_METRIC_PORT` with the desired port value to expose metrics to the Prometheus server.
    ```yaml
    environment:
      - ......
      - ......
      - JAVA_AGENT_OPTS=${JAVA_AGENT_OPTS} -Dchoreo.connect.jmx.metrics.enabled=true -javaagent:/home/wso2/lib/jmx_prometheus_javaagent-0.18.0.jar=ENFORCER_METRIC_PORT:/home/wso2/conf/prometheus_jmx_config.yml
    ```
- Add the port mapping for `ENFORCER_METRIC_PORT` in the `docker-compose.yml`.
    ```yaml
    ports:
      - .....
      - .....
      - "ENFORCER_METRIC_PORT:ENFORCER_METRIC_PORT"
    ```
- Metrics will be available at the `:ENFORCER_METRIC_PORT/metrics`.
 
 #### Adapter
 
- Add the following to `config.toml`. Replace `ADAPTER_METRIC_PORT` with the desired port value to expose metrics to the Prometheus server.
 
     ```yaml
    [adapter.metrics]
        enabled = true
        type = "prometheus"
        port = ADAPTER_METRIC_PORT
  ```
  
- Add the port mapping for `ADAPTER_METRIC_PORT` in the `docker-compose.yml`.

    ```yaml
    ports:
      - .....
      - .....
      - "ADAPTER_METRIC_PORT:ADAPTER_METRIC_PORT"
    ```
- Metrics will be available at the `:ADAPTER_METRIC_PORT/metrics`.
## On Kubernetes

#### Router

- No configuration is required. Metrics are accessible via the router admin port at the `stats/prometheus` endpoint.

#### Enforcer
- Update the `JAVA_OPTS` environment variable in the `choreo-connect-deployment.yml`. Replace `ENFORCER_METRIC_PORT` with the desired port value to expose metrics to the Prometheus server.
    ```yaml
    env:
      - name: JAVA_OPTS
        value: "....... -Dchoreo.connect.jmx.metrics.enabled=true -javaagent:/home/wso2/lib/jmx_prometheus_javaagent-0.18.0.jar=ENFORCER_METRIC_PORT:/home/wso2/conf/prometheus_jmx_config.yml"
    ```
- Add the `ENFORCER_METRIC_PORT` as a container port of the enforcer in `choreo-connect-deployment.yml`.

    ```yaml
    ports:
      - .....
      - .....
      - containerPort:ENFORCER_METRIC_PORT
    ```
- Metrics will be available at the `:ENFORCER_METRIC_PORT/metrics`.   


#### Adapter
 
- Add the following to `config-toml-configmap.yml`. Replace `ADAPTER_METRIC_PORT` with the desired port value to expose metrics to the Prometheus server.
 
  ```yaml
    [adapter.metrics]
        enabled = true
        type = "prometheus"
        port = ADAPTER_METRIC_PORT
  ```

- Add the `ADAPTER_METRIC_PORT` as a container port of the enforcer in `adapter-deployment.yml`.

    ```yaml
    ports:
      - .....
      - .....
      - containerPort:ADAPTER_METRIC_PORT
    ```
  
- Metrics will be available at the `:ADAPTER_METRIC_PORT/metrics`.

## Configuring Prometheus Server

- Incorporate the following job configurations into `prometheus.yml`.
- Substitute `ROUTER_ADMIN_PORT`,`ENFORCER_METRIC_PORT` and `ADAPTER_METRIC_PORT` with their respective values. 
- Replace `HOST` with the appropriate host address or addresses.


```yaml
scrape_configs:
  - .....
  - job_name: 'router'
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['HOST:ROUTER_ADMIN_PORT']
   
  - job_name: 'enforcer'
    static_configs:
      - targets: ['HOST:ENFORCER_METRIC_PORT']

  - job_name: 'adapter'
    static_configs:
      - targets: ['HOST:ADAPTER_METRIC_PORT']
```

NOTE: Adhere to strict security guidelines to guarantee that only the Prometheus server can access the router's admin port in production.
