### ISSUE TITLE
"mismatched input" error while build command

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-microgateway#523]
**Description:**

I got the following error while running the `micro-gw build` command.

Compiling source
    src:0.0.0
error: src:0.0.0::main.bal:9:34: mismatched input ']'. expecting {'service', 'function', 'object', 'record', 'abstract', 'client', 'from', 'int', 'byte', 'float', 'decimal', 'boolean', 'string', 'error', 'map', 'json', 'xml', 'table', 'stream', 'any', 'typedesc', 'future', 'anydata', 'new', '__init', 'foreach', 'continue', 'trap', 'untaint', 'start', 'check', 'flush', 'wait', '{', '(', '[', '+', '-', '!', '<', '~', '<-', '@', DecimalIntegerLiteral, HexIntegerLiteral, HexadecimalFloatingPointLiteral, DecimalFloatingPointNumber, BooleanLiteral, QuotedStringLiteral, SymbolicStringLiteral, Base16BlobLiteral, Base64BlobL

**Comment by bhathiya** [comment]
This was due to an error in the swagger file. 

It had the following part at the end, and unfortunately, http://editor.swagger.io didn't pick it up as an error. 

```
  '/accounts/{accountId}/instances/{instanceId}':
    parameters:
      - name: accountId
        required: true
        in: path
        type: string
        description: |
          The account ID of the owner of the specified instance.
```
