### ISSUE TITLE
OAS path-level endpoints are not supported

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-microgateway#529]
**Description:**
MG support global and HTTP verb level endpoints. But Path-level endpoints like below are not supported. 

```
paths:
  /cats:
    x-mgw-production-endpoints:
      urls:
        - http://www.mocky.io/v2/5cdc00bc2d00008415f5a4e8  
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
```
