### ISSUE TITLE
Interceptor gives a misleading error message

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-microgateway#664]
### Describe your problem(s)
The interceptor(.bal) name wouldn't be the same as a function name and also they should be exactly mapped to functions in the swagger definition.
If a function name of  the swagger definition doesn't map to the interceptor function name, It gives an error like 
"The interceptor 'validateRequest' mentioned in openAPI definition:'/Users/hasunie/RD/MC/tst/intercept/api_definitions/openapi.yaml' under path:'/store/order/{orderId}' operation:'get' is not available in the interceptors directory"

#### Please find the artefacts:
1. Interceptors directory structure
Interceptors
 |__ validateRequest.bal
 |__ validateResponse.bal

2. Swagger difinition:
```yaml
paths:
  "/pet/findByStatus":
    get:
      tags:
      - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      x-wso2-request-interceptor: validateRequest
      x-wso2-response-interceptor: validateResponse
```
3. Interceptors:

**validateRequest.bal:**
```go
import ballerina/io;
import ballerina/http;

public function validateRequest (http:Caller caller, http:Request req) {
    req.setHeader("RequesteHeader","header");
}
```

Hence the validateRequest interceptor exists in interceptors directory, Error message should be changes as 
"The interceptor 'validateRequest' mentioned in openAPI definition:'/Users/hasunie/RD/MC/tst/intercept/api_definitions/openapi.yaml' under path:'/store/order/{orderId}' operation:'get' is not available in any function in interceptors directory"
