### ISSUE TITLE
Readiness Probe is not available

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#736]
### Describe your problem(s)
Readiness probe is not included in the microgateway. This support is already there in ballerinx. This feature is required when doing a production grade deployment in K8s. https://github.com/ballerinax/kubernetes

### How will you implement it

---

**Comment by praminda** [comment]
`readinessProbe` is not available in ballerina version supported by MGW 3.0.1 ([0.990.5]). Therefore we can't include this feature in a patch release to 3.0.1. However we'll add this to next feature release in which we'll upgrade the ballerina version.

[0.990.5]: https://github.com/ballerinax/kubernetes/tree/v0.990.5

**Comment by Rajith90** [comment]
Users can specify readiness and liveness probe in the deployment .toml as below under the section [kubernetes.kubernetesDeployment]

```toml
[kubernetes.kubernetesDeployment.livenessProbe]
        enable = true
        initialDelaySeconds = '20'
        periodSeconds = '20'
    [kubernetes.kubernetesDeployment.readinessProbe]
        enable = true
        initialDelaySeconds = '30'
        periodSeconds = '30'
```
