### ISSUE TITLE
Support pulling docker images from private docker registry

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#774]
### Describe your problem(s)
This is already available in Ballerina. https://github.com/ballerinax/kubernetes/issues/147

### How will you implement it

---

**Comment by Rajith90** [comment]
This is supported with adding the imagePullSecrets property in the deployment-config.toml.
The user will have to create a kubernetes secret using the docker credentials as below in their k8s cluster

`kubectl create secret docker-registry <SECRET_NAME>  --docker-username=<USERNAME> --docker-password=<PASSWORD>`
This is also explained in the k82 doc [1].

Then users can refer the created secret in the deployment-config.toml

```toml
[kubernetes]
  [kubernetes.kubernetesDeployment]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #replicas = ''
    #enableLiveness = ''
    #initialDelaySeconds = ''
    #periodSeconds = ''
    #livenessPort = ''
    #imagePullPolicy = ''
    imagePullSecrets = ['<SECRET_NAME>']
```

[1] - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
