### ISSUE TITLE
No any OOB method to configure the response caching in wso2 Microgateway 

### ISSUE THREAD

**Issue by selakap** [wso2/product-microgateway#929]
### Describe your problem(s)
This is to create a configuration mechanism for response caching in wso2 micro gateway since the micro gateway is capable to handle the response caching 

#### Suggested Labels:
mgw

#### Affected versions:
3.0.4

**Comment by Rajith90** [comment]
We will introduce the extension **x-wso2-response-cache** with 3.1.0 beta release.
Sample extension would be as follow

```yaml
x-wso2-response-cache: 
  enabled: true
  cacheTimeoutInSeconds: 500
```
